### PR TITLE
Replacing oni and duxb* with spot.

### PR DESCRIPTION
**Pull request by rabarona**
Searched all occurrences of word oni and duxb\* in code and replaced with spot.

### CODE REVIEW

**Comment by NathanSegerlind** [comment]
I pulled the branch and I found a few more oni's in the following locations:
- many of the markdown (.md) documentation files
- oa/{dns, proxy, flow}/ipynb_templates/Threat_Investigation_master.ipynb  

and a lot of javascript and .html files (which I think are out the scope of your change)

if these are anticipated and they will be picked up when somebody else does the front end, great
otherwise, change them now

**Comment by NathanSegerlind** [comment]
ui/package.json  contains a very serious one: it still points to an oni repo

maybe it needs to be updated when we finally switch  to the new repo

**Comment by NathanSegerlind** [comment]
variations on duxbury and duxbay appear in many of the markdown doc files (*.md)

**Comment by LedaLima** [comment]
@NathanSegerlind I can take care of the notebooks references to ONI

**Comment by rabarona** [comment]
Can you please indicate which ones? Everything under ui/ folder will be taken care by @daortizh. For now, I just replaced all the backend which is everything under oa/ and components. 

ipynb files are already mentioned in Jira story DB-644.

**Comment by rabarona** [comment]
@LedaLima I added a comment in Jira DB-644 for ipynb files. That looks like HTML tags so I didn't touch that. I believe taking those in count this PR can be merged without trouble and work on those ipynb next week or next sprint along with UI changes.

**Comment by rabarona** [comment]
@NathanSegerlind  you already figured it out but just to leave a note:
- md files were updated in PR #176 
- all json, javascript, etc. under ui/ folder is going to be taken care in a different PR as it's UI related work.

**Pull request merged**
