### PR TITLE
Removed black area from maximized graphs and centered error message

### PR DESCRIPTION
**Pull request by LedaLima**
Flow Storyboard - Added a class to the maximized panels to avoid a black area to appear
Network panels - Added a class to center the text o the error message

### CODE REVIEW

**Comment by daortizh** [comment]
LGTM :+1:

**Comment by EverLoSa** [comment]
LGTM

**Comment by rabarona** [comment]
L G T M

**Comment by natedogs911** [comment]
@LedaLima nice! that was ugly. thanks for fixing

**Pull request merged**
