### PR TITLE
rename gti columns to standardize  UI

### PR DESCRIPTION
**Pull request by EverLoSa**
-Rename gti columns to standardize the UI

### CODE REVIEW

**Comment by LedaLima** [comment]
:+1:  LGTM

**Comment by NathanSegerlind** [comment]
how is this standardizing the UI?

**Comment by EverLoSa** [comment]
@NathanSegerlind  we migrated the UI framework to Flux/React  and now we are naming the columns based on the context  that we are adding to the data i.e: for srcIP we add a reputation column : srcIP_rep.
we are just keeping the original column name + the context that we are adding,  in the same way that we do in DNS. We made this change to support different reputation services

**Comment by daortizh** [comment]
LGTM :+1:

**Comment by NathanSegerlind** [comment]
LGTM

**Pull request merged**
